"""
Create Tool Tool - Allows creating custom Python tools with KB integration.
"""

import json
import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path

from knowledge import KnowledgeBase

log = logging.getLogger(__name__)


TOOLS = {
    "create_tool": {
        "name": "create_tool",
        "description": (
            "Create a custom Python tool for repetitive tasks. "
            "Tools are Python modules with a TOOLS dict export. "
            "The tool is saved to .codeassist/custom_tools/ and becomes available after reload."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Tool name (lowercase, underscores only)",
                },
                "description": {
                    "type": "string",
                    "description": "Brief description of what this tool does",
                },
                "parameters": {
                    "type": "object",
                    "description": "JSON Schema for tool parameters",
                },
                "code": {
                    "type": "string",
                    "description": "Python code for the execute() function",
                },
                "tags": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Tags for categorization",
                },
            },
            "required": ["name", "description", "parameters", "code"],
        },
    }
}


async def execute(
    name: str,
    description: str,
    parameters: dict,
    code: str,
    tags: list[str] | None = None,
    workspace: str = ".",
    session_id: str | None = None,
) -> str:
    """Create a new custom tool and log to KB."""
    try:
        # Validate tool name
        if not name.replace("_", "").isalnum() or name[0].isdigit():
            return "Error: Tool name must start with a letter and contain only letters, numbers, or underscores"
        
        # Check if tool already exists
        tool_path = Path(workspace) / ".codeassist" / "custom_tools" / f"{name}.py"
        if tool_path.exists():
            return f"Error: Tool '{name}' already exists at {tool_path}"
        
        # Check custom tools limit
        custom_tools_dir = Path(workspace) / ".codeassist" / "custom_tools"
        existing_tools = list(custom_tools_dir.glob("*.py"))
        if len(existing_tools) >= 10:
            return "Error: Maximum 10 custom tools per project. Delete unused tools first."
        
        # Ensure directory exists
        custom_tools_dir.mkdir(parents=True, exist_ok=True)
        
        # Validate code syntax
        try:
            compile(code, f"<{name}>", "exec")
        except SyntaxError as e:
            return f"Error: Invalid Python syntax: {e}"
        
        # Build the tool file content
        tool_content = f'''"""
{description}

Auto-generated by CodeAssist
"""

TOOLS = {{
    "{name}": {{
        "name": "{name}",
        "description": {json.dumps(description)},
        "parameters": {json.dumps(parameters, indent=8)}
    }}
}}


{code}
'''
        
        # Write tool file
        tool_path.write_text(tool_content, encoding="utf-8")
        
        # Log to KB
        entry_id = await KnowledgeBase.create_knowledge_entry(
            entry_type="tool_created",
            scope="project",
            scope_identifier=f".codeassist/custom_tools/{name}.py",
            content=f"Created tool '{name}': {description}",
            source_session_id=session_id,
            confidence=1.0,
            tags=tags or ["tool", "auto_created"],
            metadata={
                "tool_name": name,
                "created_by": "create_tool_tool",
            },
        )
        
        # Generate embedding for the tool
        try:
            from embeddings import get_embedding_manager
            manager = get_embedding_manager()
            import asyncio
            asyncio.create_task(manager.generate_and_store_embedding(entry_id, f"{name}: {description}"))
        except Exception as e:
            log.debug("Embedding generation skipped: %s", e)
        
        return f"✅ Tool '{name}' created successfully!\n\nLocation: {tool_path}\n\nNote: Tool will be available after server restart or manual reload."
    
    except Exception as e:
        log.exception("Failed to create tool")
        return f"Error creating tool: {e}"
